import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import buildProvidersTree from '@/components/ProvidersTree';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ProvidersTree = buildProvidersTree([]);

  return (
    <html lang="en">
      <body className={`${inter.className} container mx-auto`}>
        <ProvidersTree>
          <header className="bg-slate-500 min-h-[5vh]">Main header</header>
          <main className=" bg-slate-600 min-h-[95vh]">{children}</main>
        </ProvidersTree>
      </body>
    </html>
  );
}
